"""Add practice_area entity

Revision ID: 0e29c2c1942b
Revises: 698aa1667c7a
Create Date: 2026-09-28 14:10:07.917949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0e29c2c1942b"
down_revision: Union[str, Sequence[str], None] = "698aa1667c7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "PracticeArea",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("fags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_PracticeArea_id"), "PracticeArea", ["id"], unique=False)
    op.create_index(op.f("ix_PracticeArea_slug"), "PracticeArea", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_PracticeArea_slug"), table_name="PracticeArea")
    op.drop_index(op.f("ix_PracticeArea_id"), table_name="PracticeArea")
    op.drop_table("PracticeArea")
    # ### end Alembic commands ###
