"""add publication entity - fixed

Revision ID: 278866ab7c3b
Revises: 6a9450e6c0c5
Create Date: 2026-09-30 14:55:25.364269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "278866ab7c3b"
down_revision: Union[str, Sequence[str], None] = "6a9450e6c0c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Publications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("article", "talk", "book", "podcast", name="publication_kind_type"),
            nullable=True,
        ),
        sa.Column("venue", sa.String(), nullable=True),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Publications_id"), "Publications", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Publications_id"), table_name="Publications")
    op.drop_table("Publications")
    # ### end Alembic commands ###
