"""Add slug column in publication entity

Revision ID: 2a84c840f739
Revises: 68522f67b22e
Create Date: 2026-10-03 15:53:14.696747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a84c840f739'
down_revision: Union[str, Sequence[str], None] = '68522f67b22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Publications', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_Publications_slug'), 'Publications', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Publications_slug'), table_name='Publications')
    op.drop_column('Publications', 'slug')
    # ### end Alembic commands ###
