"""add auto-increment identity to practice_area order column

Revision ID: b2d99328a61d
Revises: 0e29c2c1942b
Create Date: 2026-09-28 14:31:41.443701

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2d99328a61d"
down_revision: Union[str, Sequence[str], None] = "0e29c2c1942b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE "PracticeArea" ALTER COLUMN "order" ADD GENERATED BY DEFAULT AS IDENTITY'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE "PracticeArea" ALTER COLUMN "order" DROP IDENTITY IF EXISTS'
    )
    # ### end Alembic commands ###
