"""add case entity modified

Revision ID: e24444db352c
Revises: 774a780b52a0
Create Date: 2026-09-29 10:48:14.169624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e24444db352c"
down_revision: Union[str, Sequence[str], None] = "774a780b52a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("result_type", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("situation", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("skills", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("featured", sa.Boolean(), nullable=True),
        sa.Column("confidential", sa.Boolean(), nullable=True),
        sa.Column("imageUrl", sa.String(), nullable=True),
        sa.Column("practice_area_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["practice_area_id"],
            ["PracticeArea.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Cases_id"), "Cases", ["id"], unique=False)
    op.create_index(op.f("ix_Cases_slug"), "Cases", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Cases_slug"), table_name="Cases")
    op.drop_index(op.f("ix_Cases_id"), table_name="Cases")
    op.drop_table("Cases")
    # ### end Alembic commands ###
