"""Add experience entity

Revision ID: fa12742424c3
Revises: 33a404bc0c09
Create Date: 2026-09-30 12:20:35.238155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa12742424c3'
down_revision: Union[str, Sequence[str], None] = '33a404bc0c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Experiences_id'), 'Experiences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Experiences_id'), table_name='Experiences')
    op.drop_table('Experiences')
    # ### end Alembic commands ###
